apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demo1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demo1
    app.kubernetes.io/part-of: purple-mermaid-app-1
  name: demo1
  namespace: rorai
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: demo1
    weight: 100
status: {}
